export const LOAD_SONG_START="LOAD_SONG_START"
export const LOAD_SONG_SUCCESS="LOAD_SONG_SUCCESS"
export const LOAD_SONG_ERROR="LOAD_SONG_ERROR"

export const CREATE_SONG_START="CREATE_SONG_START"
export const CREATE_SONG_SUCCESS="CREATE_SONG_SUCCESS"
export const CREATE_SONG_ERROR="CREATE_SONG_ERROR"

export const DELETE_SONG_START="DELETE_SONG_START"
export const DELETE_SONG_SUCCESS="DELETE_SONG_SUCCESS"
export const DELETE_SONG_ERROR="DELETE_SONG_ERROR"


export const UPDATE_SONG_START="UPDATE_SONG_START"
export const UPDATE_SONG_SUCCESS="UPDATE_SONG_SUCCESS"
export const UPDATE_SONG_ERROR="UPDATE_SONG_ERROR"
